spring:
  profiles:
    active: dev
  application:
    name: DouyinMusicService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

  kafka:

    streams:
      application-id: kafka-streams-app
      bootstrap-servers: 192.168.200.130:9092
      default:
        key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde

    bootstrap-servers: 192.168.200.130:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka