spring:
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: DouyinFileService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

server:
  port: 9011
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

minio:
  accessKey: minio
  secretKey: minio123
  bucket: good
  endpoint: http://192.168.200.130:9000
  readPath: http://192.168.200.130:9000





jwt:
  secret: root
  expiration: 86400
