server:
  port: 8080
spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  application:
    #应用的名称，可选
    name: DouyinUserService
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/douyintest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka



sa-token:
  token-name: satoken
  timeout: 86400           # Token 有效期，单位秒
  activity-timeout: -1     # 临时 Token 的有效期
  is-read-cookie: true     # 从 Cookie 中读取 Token
  is-write-cookie: true    # 将 Token 写入 Cookie
  secret-key: 123456       # Token 加密密钥
  token-dao:
    type: redis            # 使用 Redis 作为 Token 存储策略
