spring:
  application:
    name: DouyinChatService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyin_friend?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
    # 如果有密码，需要设置密码
    password:
    # Redis 数据库索引
    database: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
server:
  port: 9998
